# pubspec.yaml
name: wolfstock
description: A comprehensive stock price tracking app with AI recommendations

version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter_phoenix: ^1.1.1
  restart_app: ^1.2.1
  json_annotation: ^4.9.0
  flutter:
    sdk: flutter
  
  # State Management & Navigation
  get: ^4.6.6
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3

  # Add Razorpay
  razorpay_flutter: ^1.4.0
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Charts & Graphs
  fl_chart: ^0.66.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Formatting
  intl: ^0.19.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  pull_to_refresh: ^2.0.0
  
  # Utilities
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/animations/
