// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRvY0DkJAebQ1UWEqQ2J2J2TAY4FndCec',
    appId: '1:680538888349:web:eb0aaa01789507dc641c74',
    messagingSenderId: '680538888349',
    projectId: 'wolfstock-94f38',
    authDomain: 'wolfstock-94f38.firebaseapp.com',
    storageBucket: 'wolfstock-94f38.firebasestorage.app',
    measurementId: 'G-PH0T2GGNF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4WaJtldz2i_dWrOMnaFTon8ihfRexdBI',
    appId: '1:680538888349:android:9920800d5b864496641c74',
    messagingSenderId: '680538888349',
    projectId: 'wolfstock-94f38',
    storageBucket: 'wolfstock-94f38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr3NI6PEV_SoBx2sxFq3x82P7MpDyTvbs',
    appId: '1:680538888349:ios:c9e5fa5c095b12a3641c74',
    messagingSenderId: '680538888349',
    projectId: 'wolfstock-94f38',
    storageBucket: 'wolfstock-94f38.firebasestorage.app',
    iosBundleId: 'com.example.wolfstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr3NI6PEV_SoBx2sxFq3x82P7MpDyTvbs',
    appId: '1:680538888349:ios:c9e5fa5c095b12a3641c74',
    messagingSenderId: '680538888349',
    projectId: 'wolfstock-94f38',
    storageBucket: 'wolfstock-94f38.firebasestorage.app',
    iosBundleId: 'com.example.wolfstock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRvY0DkJAebQ1UWEqQ2J2J2TAY4FndCec',
    appId: '1:680538888349:web:72ee25a25ef775d6641c74',
    messagingSenderId: '680538888349',
    projectId: 'wolfstock-94f38',
    authDomain: 'wolfstock-94f38.firebaseapp.com',
    storageBucket: 'wolfstock-94f38.firebasestorage.app',
    measurementId: 'G-T3P3ZM80CY',
  );
}
